### ISSUE TITLE
Error: invalid ConstructorId

### ISSUE THREAD

**Issue by Mtwserv** [Widiskel/match-quest-bot#1]
**When I selected "Create session" the result is:**

```
? Welcome to Match Bot
By : Widiskel === Account undefined =============
 ame                 : undefined undefined
Lets getting started.: -
Your Session List:   : -/-
- andriiSpeed        : -
 armed Points        : -
Please Choose a menu:  -

1. Create Session.
2. Reset Sessions
3. Start Bot =================================
-
================= Account undefined =============
_
================= Account undefined =============
Name                 : undefined undefined
Balance              : -
Missions Finished    : -/-
Farming Speed        : -
Farmed Points        : -
Available Game Count : -

Status :
Delay : -
==============================================
```

**And when I selected "Start bot" the result is (phone number +111111111111 just like placeholder):** 
```
Please Choose a menu:

1. Create Session.
2. Reset Sessions
3. Start Bot

Input your choice : 3
[2024-07-30T10:22:15.014] [INFO] - [Running gramJS version 2.23.1]
[2024-07-30T10:22:15.031] [INFO] - [Connecting to 149.154.167.91:80/TCPFull...]
[2024-07-30T10:22:16.742] [INFO] - [Connection to 149.154.167.91:80/TCPFull complete!]
[2024-07-30T10:22:16.747] [INFO] - [Using LAYER 181 for initial connect]
? Enter your Telegram Phone Number ? +111111111111
[2024-07-30T10:22:41.310] [INFO] - [Phone migrated to 2]
[2024-07-30T10:22:41.381] [INFO] - [Reconnecting to new data center 2]
[2024-07-30T10:22:41.488] [WARN] - [Disconnecting...]
[2024-07-30T10:22:41.489] [INFO] - [Disconnecting from 149.154.167.91:80/TCPFull...]
[2024-07-30T10:22:41.493] [INFO] - [Connecting to 149.154.167.41:80/TCPFull...]
[2024-07-30T10:22:41.494] [INFO] - [connection closed]
[2024-07-30T10:22:42.981] [INFO] - [Connection to 149.154.167.41:80/TCPFull complete!]
[2024-07-30T10:22:42.985] [INFO] - [Using LAYER 181 for initial connect]
? Enter your Telegram Verification Code ? 79643
[2024-07-30T10:22:48.688] [INFO] - [Signed in successfully as Andrew]

[2024-07-30T10:22:49.190] [ERROR] - [Unhandled error while receiving data]
TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be
        read with ID 202659196. Most likely, a TLObject was trying to be read when
         it should not be read. Remaining bytes: 1160
    at BinaryReader.tgReadObject (C:\Users\user\match-quest-bot\node_modules\telegram\extensions\BinaryReader.js:195:31)
    at VirtualClass.readResult (C:\Users\user\match-quest-bot\node_modules\telegram\tl\api.js:451:35)
    at MTProtoSender._handleRPCResult (C:\Users\user\match-quest-bot\node_modules\telegram\network\MTProtoSender.js:554:44)
    at MTProtoSender._processMessage (C:\Users\user\match-quest-bot\node_modules\telegram\network\MTProtoSender.js:476:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MTProtoSender._recvLoop (C:\Users\user\match-quest-bot\node_modules\telegram\network\MTProtoSender.js:424:17) {
  invalidConstructorId: 202659196,
  remaining: <Buffer 7c 55 14 0c 91 02 d7 97 19 d8 5f 15 fe 77 04 00 68 74 74 70 73 3a 2f 2f 74 67 61 70 70 2e 6d 61 74 63 68 61 69 6e 2e 69 6f 2f 23 74 67 57 65 62 41 70 ... 1110 more bytes>
}
[2024-07-30T10:22:49.201] [INFO] - [Running gramJS version 2.23.1]
[2024-07-30T10:22:49.207] [INFO] - [Connecting to 149.154.167.41:80/TCPFull...]
[2024-07-30T10:22:49.255] [INFO] - [Connection to 149.154.167.41:80/TCPFull complete!]
[2024-07-30T10:22:49.261] [INFO] - [Using LAYER 181 for initial connect]

[2024-07-30T10:22:49.858] [ERROR] - [Unhandled error while receiving data]
```

**Comment by Widiskel** [comment]
try to reset the session and create session again

**Comment by Mtwserv** [comment]
> try to reset the session and create session again

**Hi,

I have reset session 5 times, but it didn't work. The result is:**

```
C:\Users\user>cd match-quest-bot

C:\Users\user\match-quest-bot>npm run start

> match-mining-bot@1.0.0 start
> node index.js

MATCHQUEST BOT
By : Widiskel
Dont forget to run git pull to keep up to date
? Welcome to Match Bot
By : Widiskel

Lets getting started.
Your Session List:
<empty>

Please enter Session Name :

Please Choose a menu:

1. Create Session.
2. Reset Sessions
3. Start Bot

Input your choice : 1
? Your session List :

<empty>

Please enter Session Name : AndrewMain
sessions\AndrewMain
[2024-07-31T10:40:28.273] [INFO] - [Running gramJS version 2.23.1]
[2024-07-31T10:40:28.292] [INFO] - [Connecting to 149.154.167.91:80/TCPFull...]
[2024-07-31T10:40:29.785] [INFO] - [Connection to 149.154.167.91:80/TCPFull complete!]
[2024-07-31T10:40:29.792] [INFO] - [Using LAYER 181 for initial connect]
? Enter your Telegram Phone Number ? +1111111111111
[2024-07-31T10:40:35.869] [INFO] - [Phone migrated to 2]
[2024-07-31T10:40:35.970] [INFO] - [Reconnecting to new data center 2]
[2024-07-31T10:40:36.061] [WARN] - [Disconnecting...]
[2024-07-31T10:40:36.062] [INFO] - [Disconnecting from 149.154.167.91:80/TCPFull...]
[2024-07-31T10:40:36.066] [INFO] - [Connecting to 149.154.167.41:80/TCPFull...]
[2024-07-31T10:40:36.068] [INFO] - [connection closed]
[2024-07-31T10:40:37.740] [INFO] - [Connection to 149.154.167.41:80/TCPFull complete!]
[2024-07-31T10:40:37.745] [INFO] - [Using LAYER 181 for initial connect]
? Enter your Telegram Verification Code ? 93286
[2024-07-31T10:40:53.858] [INFO] - [Signed in successfully as Andrew]

[2024-07-31T10:40:53.859] [WARN] - [Disconnecting...]
[2024-07-31T10:40:53.860] [INFO] - [Disconnecting from 149.154.167.41:80/TCPFull...]
[2024-07-31T10:40:53.864] [WARN] - [Disconnecting...]
[2024-07-31T10:40:53.865] [INFO] - [Disconnecting from 149.154.167.41:80/TCPFull...]
Session undefined - Created
[2024-07-31T10:40:53.880] [INFO] - [connection closed]
? Welcome to Match Bot
By : Widiskel === Account undefined =============
? Welcome to Match Bot
By : Widiskel

Lets getting started.
Your Session List:
- AndrewMain

Please Choose a menu:

1. Create Session.
2. Reset Sessions
3. Start Bot

Input your choice : 3
Error: Error reading sessions directory: TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined,
    at Helper.getSession (file:///C:/Users/user/match-quest-bot/src/utils/helper.js:82:13)
    at Telegram.onBoarding (file:///C:/Users/user/match-quest-bot/src/core/telegram.js:51:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Telegram.init (file:///C:/Users/user/match-quest-bot/src/core/telegram.js:20:7)
    at async Telegram.sessionCreation (file:///C:/Users/user/match-quest-bot/src/core/telegram.js:108:7)
    at async Telegram.onBoarding (file:///C:/Users/user/match-quest-bot/src/core/telegram.js:45:9)
    at async Telegram.init (file:///C:/Users/user/match-quest-bot/src/core/telegram.js:20:7)
    at async file:///C:/Users/user/match-quest-bot/index.js:118:9
Error: Error reading sessions directory: TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined,
    at Helper.getSession (file:///C:/Users/user/match-quest-bot/src/utils/helper.js:82:13)
    at Telegram.onBoarding (file:///C:/Users/user/match-quest-bot/src/core/telegram.js:51:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Telegram.init (file:///C:/Users/user/match-quest-bot/src/core/telegram.js:20:7)
    at async Telegram.sessionCreation (file:///C:/Users/user/match-quest-bot/src/core/telegram.js:108:7)
    at async Telegram.onBoarding (file:///C:/Users/user/match-quest-bot/src/core/telegram.js:45:9)
    at async Telegram.init (file:///C:/Users/user/match-quest-bot/src/core/telegram.js:20:7)
    at async file:///C:/Users/user/match-quest-bot/index.js:118:9
? Welcome to Match Bot
By : Widiskel

Lets getting started.
Your Session List:
- AndrewMain

Please Choose a menu:

1. Create Session.
2. Reset Sessions
3. Start Bot

Input your choice : 3
[2024-07-31T10:42:07.744] [INFO] - [Running gramJS version 2.23.1]
[2024-07-31T10:42:07.757] [INFO] - [Connecting to 149.154.167.91:80/TCPFull...]
[2024-07-31T10:42:09.395] [INFO] - [Connection to 149.154.167.91:80/TCPFull complete!]
[2024-07-31T10:42:09.400] [INFO] - [Using LAYER 181 for initial connect]
_
================= Account undefined =============
-
================= Account undefined =============
Name                 : undefined undefined
Balance              : -
Missions Finished    : -/-
Farming Speed        : -
Farmed Points        : -
Available Game Count : -

Status :
Delay : -
==============================================
```

**Maybe I need to install a specific version of NODE JS or NPM?
I currently have the following versions:
Node JS v20.16.0
NPM 10.8.1**

**Comment by Widiskel** [comment]
ahh i see, the issue is because telegram force upgrade versions of gram js to 2.23.^, to resolve this issue, run
```npm i telegram@2.22.2```

and make sure PROJECT/node_modules/telegram/Version.js have this value

```
exports.version = "2.22.1";
```

**Comment by Mtwserv** [comment]
> ahh i see, the issue is because telegram force upgrade versions of gram js to 2.23.^, to resolve this issue, run `npm i telegram@2.22.2`
> 
> and make sure PROJECT/node_modules/telegram/Version.js have this value
> 
> ```
> exports.version = "2.22.1";
> ```

It's working now. 
Thank you very much for your help and for creating the bot. 
Please tell me if this bot has problems with the reward for games if you set more than 200 coins in the game configuration? Are there any errors with the games or not?

**Comment by Widiskel** [comment]
the reward wouldn't counted, so it will waste of ticket. im already try it, max is 200 i think

**Comment by Mtwserv** [comment]
> the reward wouldn't counted, so it will waste of ticket. im already try it, max is 200 i think
Thank you very much for the information. I thought so.
